[project]
name = "podcast-scrapers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.12.2",
    "dotenv>=0.9.9",
    "feedparser>=6.0.12",
    "requests>=2.32.5",
]
