version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
    - "9092:9092"   # internal container-to-container listener (optional)
    - "29092:29092" # host-accessible listener for tools on Windows

    env_file:
      - ../.env
    volumes:
      - podcast-data:/var/lib/kafka/data
    networks:
      - podcast-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 5

  podcast-scraper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: podcast-scraper
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../data:/app/data
    networks:
      - podcast-network
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  podcast-data:
    driver: local

networks:
  podcast-network:
    driver: bridge


